import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :folio, FolioWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No `force_ssl` on purpose. Folio is self-hosted and only ever binds a plain HTTP
# socket, so redirecting to https:// would point at a port it does not listen on.
# TLS termination, the http -> https redirect and HSTS belong to whatever reverse
# proxy sits in front. Set SCHEME=https (see config/runtime.exs) to tell Folio it is
# reached over https, so generated URLs and the session cookie match.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
